### ISSUE TITLE
Devcontainer gopls out of date

### ISSUE THREAD

**Issue by bengreenier** [lawrencegripper/azbrowse#209]
The Go extension complains about out of date `gopls` when opening the container.

> Note: If you choose to update, it seems to persist it into the container (until it is rebuilt), so it's not everytime the project is opened.

![image](https://user-images.githubusercontent.com/1167891/71815722-4f211b80-3078-11ea-8950-4f7d81741188.png)

As I understand it, `gopls` is alpha, so maybe this pinned version is intentional and the error should be ignored?

Seems there's 1 of 2 actions to take here:
+ Document that you should close/ignore the popup error
+ Update the Dockerfile to use [`gopls@v0.2.2`](https://github.com/golang/tools/releases/tag/gopls%2Fv0.2.2)

**Comment by lawrencegripper** [comment]
My bad here, did a bad job of doc'ing decisions here. I pinned the version so that everyone would always have the same devcontainer environment and update would be an explicit step. (Maybe too paranoid of me but as also using the container for the build didn't want a release to cause an issue.)

If we can take the newer version and it plays nice then I'm all for updating the version.
