### ISSUE TITLE
Run out of space to draw the `Pending delete` list!

### ISSUE THREAD

**Issue by daltskin** [lawrencegripper/azbrowse#331]
Not sure if this is a bug or by design to limit number of pending deletes?

When adding multiple items to delete to the 'pending delete' list I hit this issue:

Can't add `["some-file"] ABC-ID` run out of space to draw the `Pending delete` list!

![image](https://user-images.githubusercontent.com/1678318/115033155-ffa7dd00-9ec1-11eb-9c6b-3d304477e1d2.png)

**Comment by daltskin** [comment]
Ah, just noticed it's a window sizing message - if I make the window bigger, I can have a bigger pending delete list :)

**Comment by lawrencegripper** [comment]
Yeah turns out there is some code to make sure you don't add more items than can be draw. Forgot about that!

https://github.com/lawrencegripper/azbrowse/blob/999766b545e59a7e9b77b210230176fa3fd65aba/internal/pkg/views/notifications.go#L56

Was your window the same size as in the screenshot when the error occurred? Shouldn't have stopped our at that size as should only stop when 12 lines left (the number needed to draw the other bits of the view and buffer)

**Comment by daltskin** [comment]
Yep, you're right, I think I must have resized the window to take the screenshot.  Makes sense that this guard is in there.

There is a minor issue then if you resize the window to make it bigger once you've seen the warning message 'Can't add [some-file]`, as you can still add items to the pending list (as there will be enough screen estate), but the status message doesn't get cleared.

So steps to reproduce:

- Delete a bunch of files until you hit the `Can't add [some-file]` message
- Make the window bigger
- Delete more files (they'll successfully get added to the pending list)
- The status message will still show the `Can't add [some-file]` message.

So not sure the message timeout is working, or could maybe clear the status message when window resizes?

**Comment by lawrencegripper** [comment]
Think I have this resolved by giving some feedback when items are successfully added to the pending delete queue. This overwrites the failed status message, bonus is it's more informative.
