### ISSUE TITLE
Suggestion: Move the position of the status icons

### ISSUE THREAD

**Issue by martinpeck** [lawrencegripper/azbrowse#69]
For resources with long names it hard/impossible to see the status icons.

Without checking how easy it would be, can we move the status icon to the left of the resource name, rather than at the end? This will also make it easier to scan down the list and spot issues.

![image](https://user-images.githubusercontent.com/1524451/53525255-3c919980-3ad9-11e9-9e45-5925ede5feab.png)

**Comment by jjcollinge** [comment]
I think this would be doable but to make it cleaner I would suggest if we add this icon at the front we change the selection indicator from an arrow to a block colour highlight .i.e. the selected rows are a lighter shade (we'd have to test with different colour schemes too).

**Comment by lawrencegripper** [comment]
Had a big of play... this turns out to be harder than you'd initially think to make it play nice. 

The other issue I have with moving the status icon to the left is that it's secondary data (for me) so I don't want it to distract from the name etc which I'm trying to read. 

Having it on the left feels much harder to read the text ..

![maybe](https://user-images.githubusercontent.com/1939288/53568412-db5dda80-3b59-11e9-9b5d-d87089711852.gif)
![nope2](https://user-images.githubusercontent.com/1939288/53568413-dbf67100-3b59-11e9-8ef6-3d1eaa42f7a8.gif) 
![nope](https://user-images.githubusercontent.com/1939288/53568414-dbf67100-3b59-11e9-82c3-685bd8170ba3.gif)
![notsure-select](https://user-images.githubusercontent.com/1939288/53568415-dbf67100-3b59-11e9-8c4d-d16920cb1013.gif)

**Comment by lawrencegripper** [comment]
### Background highlight

![peek 2019-02-28 14-02](https://user-images.githubusercontent.com/1939288/53571765-963da680-3b61-11e9-97b2-df98ded16b17.gif)

One more option

**Comment by martinpeck** [comment]
In terms of the icon, leave it where it is. I did wonder if having them on the left but only having icons for the non-happy state (i.e. the sun would no longer be present) was a good idea. That means you can see things that have problems, and when everything is fine the icons are gone. But, I say leave it for now.

In terms of the pointer/highlighter. I would avoid any sort of colour highlighting (accessibility). Of the options above, the current arrow is best IMO. I wonder if it should point at the name, not the resource type (it always feels oddly misaligned to me), but other than that I think it's fine. 

Given the title of this issue, I'm happy if you close this.

**Comment by jjcollinge** [comment]
Fair, as a colour blind person I appreciate the block colour highlight would have to be high contrast for accessibility so the arrow is easier to see. Does it make more sense to reverse the current order rather than the pointer (name then resource?). I am not sure, just asking?

**Comment by lawrencegripper** [comment]
Hmmm that would be interesting one to play with. In terms of reducing noise and improving readability I also like that idea from @martinpeck of removing the `sunshine` from items and having that be implicit... only drawing a status icon where the resource is in a non-success state. 

What do you think?

**Comment by jjcollinge** [comment]
Just a note: If you used the colour highlight we could add a multiselect functionality that'd be support handy for deletion of resources

**Comment by lawrencegripper** [comment]
ooooh multi select for deleting... now your talking. This will require so more thought but I'd love to add that feature regardless of how the items are shown as selected.

**Comment by jjcollinge** [comment]
Created new issue #76 to track this

**Comment by lawrencegripper** [comment]
Going to close this one out for now as don't think we came up with a good alternative. Happy to re-open if we have a good option.

**Comment by martinpeck** [comment]
Agreed.
